### ISSUE TITLE
Flatpak or Appimage

### ISSUE THREAD

**Issue by ahmed-tasaly** [ShaanCoding/makeread.me#14]
Assalam Alaykom

## Feature Details

Can you create Flatpak and Appimage versions ?

_Thanks in advance_

**Comment by ShaanCoding** [comment]
Hi @ahmed-tasaly, thanks for raising this suggestion & sorry for the delay.

I've been very busy recently and haven't had the time to work on this project till recently. Would you be able to elaborate more on what you mean by adding flatpak / appimage readmes, and would you have an example on how these ReadME's would differ? I'm not familiar with these technologies.

Outside of that, with the version 2 rebuild of this ReadME Generator, I've added support for users to create & contribute their own templates, which you can see in the backend/public folder.

If you're interested you can also feel free to contribute your own template if you think it provides value.

Thanks,
Shaan
