### ISSUE TITLE
Add Preview Modal

### ISSUE THREAD

**Issue by ShaanCoding** [ShaanCoding/makeread.me#34]
## Feature Details

We are starting to get quite a few read-me templates generated and some users may not want to jump between pages to find their readme. This is also somewhat slow as we're using NextJS and it is not a SPA. As a result there is loading time between page navigation.

I'm thinking we can make a preview Modal appear on the template screen to allow users to preview what a finalised ReadME / template may look like.... To investigate more later

![image](https://github.com/ShaanCoding/makeread.me/assets/22236218/189234a6-f64c-435a-b3e4-46994b314748)

**Comment by ShaanCoding** [comment]
FYI for this, you can probably use the stylised rendering component we've made, as part of this you can also try to uplift #53... The defects of this is it breaks / is not super responsive compared to github as in it renders inconsistently to what markdown should render as

**Comment by ShaanCoding** [comment]
@MathPow almost done this ticket FYI

**Comment by MathPow** [comment]
Good job. Looking good!
