### ISSUE TITLE
Add Contextual Help & Tooltips

### ISSUE THREAD

**Issue by ShaanCoding** [ShaanCoding/makeread.me#54]
## Feature Details

To look more into later & refine

Provide contextual help & tooltips to guide the user on the ReadME creation process
I.e. userfield would have a tooltip, saying (Please enter your github username)

**Comment by MathPow** [comment]
Hi Shaan. I could do something about it. I did something similar in my other project. If you could give me more details about what is the perfect user walkthrough, it would be awesome. Do you have an example that you found online about a design for contextual help? Maybe something like this would help users know where to go and what to do on there first visite.

![image](https://github.com/ShaanCoding/makeread.me/assets/75903735/cf937b81-75d8-4dc0-ad19-39dd90489b94)
OR
![image](https://github.com/ShaanCoding/makeread.me/assets/75903735/9f80a4ca-7a24-4883-b3d3-afe289ebc016)


 I will do it in my free time, so it could take some days.

**Comment by ShaanCoding** [comment]
Hey @MathPow thanks again for wanting to pick this work up! It would save me a lot of time as there's a lot of features / tickets I've got to work through 😆

In regards to this one, it was just a suggestion I've been given from user-feedback, I don't yet quite have an onboarding flow envisioned. I'll follow up here shortly once I work-out a non-intrusive user-flow and have a better idea of what this feature would entail.

Though at the current moment for this feature, I was thinking more of the following functionality:
![image](https://github.com/ShaanCoding/makeread.me/assets/22236218/3a83ea60-5926-4bfd-9703-673431ac1aed)
With a info icon, like the one below
![image](https://github.com/ShaanCoding/makeread.me/assets/22236218/53b48510-04d4-4265-8f43-b71ddb8ef2ae)
Explaining the use-case of the variable i.e. Logo URL would have a info icon with the description: "Logo URL specifies the image the project logo should take and render, can use relative paths from the repository this will be in or a direct URL" for example
![image](https://github.com/ShaanCoding/makeread.me/assets/22236218/78d4fe97-9d75-4460-966e-dc93b8b83e1a)

**Comment by ShaanCoding** [comment]
FYI this would involve extending our schema to have a description type, regenerating our frontend types to support this and then creating the tooltip icon to render it. This project uses `shacn/ui` and they already have a tooltip icon, so this functionality should be fairly small / easy to implement (fingers crossed).

Have a look at the following for help in implementation: https://ui.shadcn.com/docs/components/tooltip & for icons we use lucide-react https://lucide.dev/guide/packages/lucide-react

**Comment by MathPow** [comment]
Thank you for the details. I see what to do now. It will be a pretty easy task and I already know how to use Shadcn. I will look into the library for the icons.

Do you want me to generate the descriptions or you will give me a list?
 
Is there a other task after this one that would help you a lot?

**Comment by MathPow** [comment]
Where did you found the form with "Logo URL" and all that?

**Comment by ShaanCoding** [comment]
This text is available in the "Project Header" block on Othneil Drew's ReadME available here: https://www.makeread.me/generator/othneildrew-best-readme-template

This is just an example, all inputs and blocks should have this tooltip as an additional extra.

**Comment by MathPow** [comment]
Found it! :)

**Comment by ShaanCoding** [comment]
Feel free to add a description / do whatever you think is easiest.

I'm looking to redo these templates in the near future to remove some of the bugginess / inconsistencies as I've added a few more data types since creating the first template.

After this ticket, depending on how much time you have, feel free to pick up one of the following:

- https://github.com/ShaanCoding/makeread.me/issues/49
- https://github.com/ShaanCoding/makeread.me/issues/36
- https://github.com/ShaanCoding/makeread.me/issues/50
- https://github.com/ShaanCoding/makeread.me/issues/53
