### ISSUE TITLE
feat: redesign the template Page

### ISSUE THREAD

**Issue by MathPow** [ShaanCoding/makeread.me#69]
## Feature Details

- Page layout that have a search bar.
- Page layout that have tag filter system.
- Page layout that have tab to filter différent type of documents.

## Other change ideas to be reviewed and open issue for (if passed 💯)  @ShaanCoding 

- Rename page to templates (template -> templates).
- User can favorite templates and review it in a tab. We can stock the data in the local storage. It would add a touch of customizability so the user would want to come back every time they want markdown.
- Start from an empty template.
- Redesign the card layout to take less space.

## Figma

![image](https://github.com/ShaanCoding/makeread.me/assets/75903735/e8eab96c-680d-4742-9b7f-4d74d61f882c)
![image](https://github.com/ShaanCoding/makeread.me/assets/75903735/da566908-1319-4462-a26e-c43b0a0b0c01)
![image](https://github.com/ShaanCoding/makeread.me/assets/75903735/b5b77c3b-7ca6-46ab-bc73-8cf609955f52)

## Inspirations

![image](https://github.com/ShaanCoding/makeread.me/assets/75903735/6148a8de-29e2-444d-986a-abd8634217f4)

![image](https://github.com/ShaanCoding/makeread.me/assets/75903735/92974ade-0e73-4ad9-bdc5-550b553fb0ad) (canvas.com) but less childish

**Comment by ShaanCoding** [comment]
Hi Matt, thanks for the contributions and designs again! I've added you to the Figma to preview and love the work you've done in proposing some UI/UX designs. I definitely agree that the current page-layout is not scalable and have just implemented these suggestions as requested. As a summary:

## Done the following
- Page layout that have a search bar. ✅ #47 #47
- Page layout that have tag filter system. ✅ #49 #47
- Page layout that have tab to filter différent type of documents. ✅ #47 

## Will Do

- [ ] Start from an empty template, will be scoped to a new issue / feature
- [ ] Users can favorite, can be rescoped to a new issue / feature
- [ ] Preview is a pre-existing ticket I'll add screenshot / previews there

Let me know if I've missed anything

**Comment by ShaanCoding** [comment]
Closing this issue as it's being tracked in other issues 👍 Awesome contribution again!

**Comment by ShaanCoding** [comment]
Closing this issue as it's being tracked in other issues 👍 Awesome contribution again!
