### ISSUE TITLE
feat: contributors page on the web site

### ISSUE THREAD

**Issue by MathPow** [ShaanCoding/makeread.me#72]
A page where all contributors with their linkedin and github link are listed. It would encourage contributors to help so they can be appart of this page. It shows gratidute and people want to be seen

Information for one person card:
- Name
- Small custom description
- First PR date
- Github
- LinkedIn

**Comment by ShaanCoding** [comment]
Happy to follow with this one & even make it dynamic with an API call to grab all contributors. Probably will keep this on the backlog with #20 

I do want to credit @MathPow, and @dukeofsoftware who contributed to the MVP of this project

**Comment by MathPow** [comment]
Here's some inspirations: 
![image](https://github.com/ShaanCoding/makeread.me/assets/75903735/3dc652ab-f68c-4fcf-a7f4-6c50f8df1299)

**Comment by ShaanCoding** [comment]
![Contributions Page Idea](https://github.com/ShaanCoding/makeread.me/assets/22236218/017064d4-aedd-4968-b9ab-65c2715f5e47)

Being worked on by @bobrandy13 in #83 but as discussed it should be the following requirements:

# User Story

As a user, I would like to have a minimalistic 'Our Team' page to easily understand the contributions of team members.

## Description

This user story encompasses creating an 'Our Team' page that displays information about different teams in our organization namely; Development, Design, Template Contribution, and Bug Reports & Documentation. This page will be similar to the React team's page layout, available here: [React Team](https://react.dev/community/team). The page should be simple and render some introductory text with a H1 of 'Our Contributors' (these should be parameters from a config page like the site.ts file) and four sections for each team. Each sections contributor should be displayed as a single block or card layout with a show/hide button. By default, only the minimized view is shown but should have an option to switch to a detailed view with all contributions and details.

## Acceptance Criteria

1. The page is able to render and display a 'Our Contributors' H1 title.
2. Each team's section (Development, Design, Template Contribution, Bug Reports & Documentation) is displayed as a single block or card layout.
3. Each block has a show/hide button that displays a minimized view by default.
4. An option to switch to a large view to display all contributions and details is available.
5. Parameters are pulled from a config page like the site.ts file.

## Other Notes
- Use semantically correct HTML when applicable https://www.w3schools.com/html/html5_semantic_elements.asp
- Use the shadcn/ui components when possible as they're made to be accessible & are consistently formatted with the rest of our application currently
- By default we like doing spacings of mb-2, mb-3 and mb-6 for spacing. Copy the same format we've done for other pages when applicable for consistency sake

## Tech Notes

The parameters for the 'Our Contributors' H1 title and the introductory text will be pulled from the site.ts config file. The show/hide functionality will need to be implemented for each section. By default, the minimized view will be displayed but functionality to switch to a large view should also be added. The layout for each block will be similar to our other blocks.

**Comment by ShaanCoding** [comment]
Done in #83
