### ISSUE TITLE
Add The Ability for Users to Favorite Templates

### ISSUE THREAD

**Issue by ShaanCoding** [ShaanCoding/makeread.me#77]
## Feature Details

Using localstorage to add the ability for users to favorite templates, as mentioned in #69

**Comment by MathPow** [comment]
If we are going to stick with the current card design, how will the user "star" a template? Do we add a icon? Where do we put it?

**Comment by ShaanCoding** [comment]
I will follow up later today with some refinements of requirements on this one. Thanks for wanting to pick this work up

**Comment by ShaanCoding** [comment]
Pending Review of #93
