### ISSUE TITLE
Cannot add blocks from the current template

### ISSUE THREAD

**Issue by MathPow** [ShaanCoding/makeread.me#92]
## Describe the bug
When we add blocks from the current template, nothing seems to update in the preview but we can see the change in the blocks area. If we select "Add Block" from an other template on the right (with the new feature), it works fine.

## To Reproduce

1. Go to othneildrew-best-readme-template
2. Click on 'Add Block' from any of the option of the right. It needs to be a block from the current template
3. Scroll down to the bottom of the page
4. See that nothing updates in the preview

## Expected behavior
We want the markedown preview to update in real time everytime

## Screenshots
![image](https://github.com/ShaanCoding/makeread.me/assets/75903735/92dbe080-0363-460e-ad28-d48fa61aee2a)

**Comment by ShaanCoding** [comment]
To remove this pain point, I'm going to 'fix' this by enforcing 1 unique block per project for now. I'll make a follow-up ticket removing this restriction later
